spring:
  main:
    banner-mode: "off" # Requires to be quoted
  application:
    name: my-api
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:myDB
    username: todos
    password: secret
  liquibase:
    enabled: true
    url: jdbc:h2:mem:myDB
    user: todos
    password: secret
    change-log: "classpath:db/liquibase-changelog.yaml"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
#      database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false

server:
  port: 8000

logging:
  level:
    com.todos: debug